[package]
name = "audio_visualizer"
version = "0.1.0"
authors = ["Patric Kanngießer <mail@lpnw.de>"]
edition = "2018"

[dependencies]
rustfft = "3.0.0"
apodize = "1.0.0"
libpulse-binding = "2.6.0"
libpulse-simple-binding = "2.6.1"
sdl2 = "0.32.2"
hound = "3.4.0"